const VAR = {};

// Response Code (RC)
VAR.RC_OK = 200; // OK
VAR.RC_CREATED = 201; // after CREATE or UPDATE
VAR.RC_NO_CONTENT = 204; // after DELETE
VAR.RC_REDIRECT = 302;
VAR.RC_BAD_REQUEST = 400;
VAR.RC_NO_AUTH = 401;
VAR.RC_FORBINDEN = 403;
VAR.RC_NOT_FOUND = 404;
VAR.RC_TIMEOUT = 408;
VAR.RC_INTERNAL_ERR = 500;
VAR.RC_NO_IMPLEMENT = 501;
VAR.RC_SERV_UNAVAILABLE = 503;

// Error Code (EC)
VAR.OK = 'OK';
VAR.SUCCESS = 'Success';
VAR.ERROR = 'Error';
VAR.ERR_DATA = 'Invalid Data';
VAR.INVALID_EMAIL = 'Invalid Email Format';
VAR.INVALID_PASSWORD = 'Invalid Password Format';
VAR.INVALID_MODEL = 'Invalid Model';
VAR.ALREADY_SWMAC = 'Already switch the mac';
VAR.STR_TOO_SHORT = 'String length is too short';
VAR.STR_TOO_LONG = 'String length is too long';
VAR.DB_ERROR = 'Database error';
VAR.TIMEOUT = 'Request timeout';
VAR.PARAMETER_ERROR = 'Wrong parameters';
VAR.DUP_REG = 'The register address has been used';
VAR.DUP_DEV = 'The device already exists';
VAR.DUP_COMP = 'The company already exists';
VAR.DEV_JOINED = 'This device has joined to a company';
VAR.DUP_USER = 'The user already exists';
VAR.DUP_LOGIN = 'The user already login in another device';
VAR.DUP_FILE = 'The file already exists';
VAR.DUP_GROUP = 'The group already exists';
VAR.DUP_GROUP_MEMBER = 'The group member already exists';
VAR.VAR_NDEF = 'Some parameters are undefined';
VAR.NO_HEAD_PERMISSION = 'Only head Datalogger have write permission';
VAR.NO_HEAD_DLOG = 'Can\'t find head Datalogger!';
VAR.OTHER_DLOG = 'The device is in another Datalogger';
VAR.INVALID_DATA = 'Invalid Data';
VAR.DEV_LOGGING = 'Device is logging';
VAR.NO_ANY_LOG_REG = 'No any logging registers';
VAR.NO_DEV = 'No such device';
VAR.NO_FILE = 'No such file';
VAR.NO_USER = 'No such user';
VAR.NO_COMP = 'No such company';
VAR.NO_SUPPORT = 'No support';
VAR.NO_RECORD = 'No any record';
VAR.NO_GROUP = 'No such group';
VAR.NO_GROUP_MEMBER = 'No any group member';
VAR.NO_DATA = 'No data';
VAR.NO_REG = 'No such register';
VAR.NO_ALLOW_WR = 'Not allow to write';
VAR.NO_ALLOW_RD = 'Not allow to read';
VAR.NO_ALLOW_NAME_ADMIN = 'Username cannot be Admin';
VAR.NO_FW = 'No upgade firmware';
VAR.NO_FW_KEY = 'No firmware key';
VAR.NO_SUPPORT = 'No support';
VAR.AUTH_FAIL = 'Authenication failed';
VAR.NO_PERMISSION = 'Permission denied';
VAR.NO_AUTH = 'No authenication, please login';
VAR.NO_PUSHID = 'Push ID Not found';
VAR.NO_ACTIVATE = 'Need account activaction';
VAR.NO_MORE_SPACE = 'No more space';
VAR.NO_MORE_REGS = 'No more available registers';
VAR.ALM_DISABLED = 'The device alarm has been disabled';
VAR.NO_AVAIL_ACCOUNT = 'No available accounts!';
VAR.ALREADY_LOGIN = 'Already login';
VAR.ALREADY_LOGOUT = 'Already logout';
VAR.ALREADY_LATEST_VER = 'Already the latest version';
VAR.CHG_SLEF = 'The setting will be applied the next time you logout';
VAR.NOT_ALLOW = 'The operation is not allowed in this situation';
VAR.PARSE_ERR = 'Failed to parse file';
VAR.MAX_COMPANY = ' The maximum number of company has been reached';
VAR.MAX_USER = ' The maximum number of user has been reached';
VAR.MAX_DEVICE = ' The maximum number of device has been reached';
VAR.MAX_CTRLBLK = ' The maximum number of control block has been reached';
VAR.MAX_BRICK = ' The maximum number of IXO view has been reached';
VAR.MAX_GROUP = ' The maximum number of Group has been reached';
VAR.MAX_GROUP_MEMBER = ' The maximum number of Group member has been reached';
VAR.MAX_ANNOUNCE = ' The maximum number of announcement has been reached';
VAR.MAX_FILE_LINK = ' The maximum number of url link has been reached';
VAR.SEND_TOO_FAST = 'Send requests too fast!';

module.exports = VAR;
